
modLoader="javafml"
loaderVersion="[35,)"
license="GNU 3.0"
issueTrackerURL="https://github.com/Wadoo-Gazoono/Hyperion/issues" #optional
 
[[mods]] #mandatory
modId="hyperion"
version="0.0.1"
displayName="Hyperion"
displayURL="https://www.curseforge.com/minecraft/mc-mods/hyperion"
logoFile="hyperion.png"
authors="Wadoo, Virtualhel, and Naz"
description='''
A Nether mod that adds new and interesting mechanics, mobs, and more!
''' #mandatory