
modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="GNU 3.0" #mandatory https://choosealicense.com/
issueTrackerURL="http://my.issue.tracker/" #optional
 
[[mods]] #mandatory
modId="hyperion" #mandatory
version="0.0.1" #mandatory
displayName="Hyperion" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="http://example.com/" #optional
logoFile="examplemod.png" #optional
credits="The credits for your mod." #optional
authors="Programming: Wadoo and Naz Texturing: Virtualhel and HauntedChest" #optional
description='''
A Mod that strengthens the Nether portion of a Minecraft playthrough.
''' #mandatory